### ISSUE TITLE
checkra1n download URL incorrect

### ISSUE THREAD

**Issue by FedeltaMedia** [7OU/cumbox#10]
In the file  rainpi/install-arm.sh you're using an incorrect download link for checkra1n:
`wget https://assets.checkra.in/downloads/linux/cli/arm/c5cbb125c6948b39383702b62cec4f184263c8db50f49b9328013213126dae78/checkra1n -P /opt/cumbox`

checkra1n generates a unique downloadlink, so the code after '....downloads/linux/cli/arm/' is randomly generated. Meaning, this script will never work.

**Comment by m1stadev** [comment]
...no it doesn’t? the code in the URL is just the sha256 of the checkra1n binary. the only time the script will need changing is for later versions of checkra1n.

**Comment by evaan** [comment]
what m1sta said, closed.
