### ISSUE TITLE
Is Really a jumper wire required?

### ISSUE THREAD

**Issue by ghost** [7OU/cumbox#5]
Title

**Comment by evaan** [comment]
For the python one, yes.

**Comment by ghost** [comment]
> For the python one, yes.

i have a raspberry pi 4 with a fan, im a noob on this, but where i can get the jumper wires?

**Comment by ReubenBTalbott** [comment]
you could just jumper it with a paper clip or other piece of wire, just be careful or you might let out the magic smoke😊

**Comment by evaan** [comment]
a udev rule will be added soon
