### ISSUE TITLE
Raspberry Pi 1 Model B (Non Plus) GPIO Pinout

### ISSUE THREAD

**Issue by nate-moo** [7OU/cumbox#8]
Hello, I have a raspberry pi 1 and the pinout is different compared to the diagram you are showing on the readme.md page. is there a different pinout image for this raspberry pi? The model B(Non plus) has 26 pins, while the newer ones have 38 pins

**Comment by nate-moo** [comment]
I am just getting my raspberry pi ready for the checkra1n for linux comes out

**Comment by evaan** [comment]
youll just have to modify it
