### ISSUE TITLE
checkra1n has linux

### ISSUE THREAD

**Issue by untuned** [7OU/cumbox#9]
https://checkra.in/releases/0.9.8-beta

**Comment by gill6151** [comment]
no linux has checkra1n

**Comment by FedeltaMedia** [comment]
This will probably never get updated. Just use https://ra1nbox.com ;-)

**Comment by evaan** [comment]
I’m currently not home and won’t be for the next week, might archive it unless someone wants to actually do something.

**Comment by evaan** [comment]
Updated.
